"""
Falsification test stubs for claim: "we are moving in the direction the maintainer
wants (SOLID, component principles, screaming architecture, WET-before-DRY) while
allowing new APIs to be set up ASAP"
Generated by /falsify audit on 2026-07-31, after þing-02 closed.

Verdict was FALSIFIED: 4 hard, 2 soft, 1 survived-with-a-gap.

These tests are in TDD RED state -- they FAIL against the current repository and
platform. Fix the underlying findings to make them pass, then re-run /falsify to
verify and check for regressions.

The systemic finding underneath all of them: this platform enforces its rules on
code and states them in prose. Every hard falsification is the same shape -- a
ratified rule with no mechanical check.

Two findings from that audit are NOT stubbed here because they were fixed in the
same change-set and now have live checks instead:
  - C-33 (contract/registry version drift) -> docs/validate_docs.sh check 7
  - C-39 (issue #10's body carried the superseded S17 ordering) -> the contract
    now states the ratified D4 order; the issue was closed naming the error
The remaining six have no check and no fix, and are red below.

NOTE: This file makes the `ship-it` pytest gate red on purpose. That is the
TDD-red contract of the falsification audit, not an accident. Do not delete these
to make a gate pass.
"""

import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PLATFORM = REPO / "docs" / "ADRs" / "platform"
CONTRACT = PLATFORM / "appwrite_seam_contract.md"
REGISTRY = PLATFORM / "coordinate_registry.toml"
WORKSPACE = REPO.parent

CONSUMERS = (
    "views-faoapi",
    "views-models",
    "views-pipeline-core",
    "views-postprocessing",
    "views-datafactory",
)


def test_falsify_c37_contract_has_one_reason_to_change():
    """
    Probe P3 (Category E): SRP/CCP applied to the contract itself.

    Finding: PLATFORM-001 has FOUR change-drivers in one file -- normative rules,
    observed console state (§2), deliberation history (§11), and an open-item
    ledger (§9). They change on unrelated schedules and serve different audiences.
    An operator rotating a key forces a version bump on a document whose rules did
    not move, and a consumer diffing two versions cannot separate "a rule changed"
    from "someone looked at a console".
    Severity: hard

    Expected: observed state lives in the registry (which already has `observed`
    fields per slot); history lives in the þing record (which already holds it in
    full); the contract holds rules.
    """
    text = CONTRACT.read_text(encoding="utf-8")
    has_observed_state = "Observed state" in text
    has_amendment_log = "## 11. Amendment Log" in text
    has_open_ledger = "## 9. Open items" in text
    drivers = sum((has_observed_state, has_amendment_log, has_open_ledger))
    assert drivers <= 1, (
        f"PLATFORM-001 carries {drivers + 1} change-drivers in one file "
        "(rules + observed state + history + open-item ledger). "
        "SRP/CCP: things that change together live together; these do not change together."
    )


def test_falsify_c40_every_consumer_pins_the_contract():
    """
    Probe P6 (Category B): the pin rule (þing-01 E2) vs reality.

    Finding: of five consumer repos, ONE pins to a commit (views-models, to
    60674b2 -- which is v1.0.0, two versions stale), ONE links to /blob/main/
    (views-datafactory/docs/guides/credential_setup.md:15 -- not a pin at all,
    and it silently changed meaning when v1.2.0 landed), and THREE cite the
    contract by name with no reference. Ratified at þing-01, never enforced,
    never audited.
    Severity: hard

    Expected: every consumer that references PLATFORM-001 does so at a pinned
    tag or commit -- never at /blob/main/, never by bare name.
    """
    offenders = []
    for repo in CONSUMERS:
        root = WORKSPACE / repo
        if not root.exists():
            continue
        hits = subprocess.run(
            ["grep", "-rl", "PLATFORM-001", str(root), "--include=*.md", "--include=*.py"],
            capture_output=True, text=True,
        ).stdout.split()
        if not hits:
            continue
        blob = " ".join(Path(h).read_text(encoding="utf-8", errors="ignore") for h in hits)
        if "/blob/main/" in blob and "PLATFORM-001" in blob:
            offenders.append(f"{repo}: links to /blob/main/ (a moving target, not a pin)")
        elif not re.search(r"/blob/(?:[0-9a-f]{7,40}|platform-001-v[\d.]+)/", blob):
            offenders.append(f"{repo}: cites PLATFORM-001 by name with no pinned reference")
    assert not offenders, "Consumers not pinning the contract:\n  " + "\n  ".join(offenders)


def test_falsify_c38_conformance_vector_released_with_its_consumers():
    """
    Probe P4 (Category B): REP applied to the conformance vector.

    Finding: the vector and the three thin clients (faoapi, un-crafdapi,
    views-productionapi) are REUSED together -- every clone runs it -- but
    RELEASED separately: the vector versions with PLATFORM-001, the clients
    version independently. Change the vector and three clients silently fall out
    of conformance, with nothing triggering a re-run. þing-02 has no clause for
    this; the gap was found by applying the maintainer's own REP principle, which
    the þing record never uses.
    Severity: soft

    Expected: the vector exists, and carries a stated mechanism binding its
    version to the clients that must run it.
    """
    vector = list(PLATFORM.glob("conformance*")) + list(PLATFORM.glob("*vector*"))
    assert vector, (
        "The conformance test vector (þing-02 A4, issue #13) does not exist yet. "
        "It is a precondition of the first clone and must be authored from faoapi's "
        "POST-SALT implementation -- written before the salt, it encodes the fused "
        "behaviour as the reference and every clone conforms to the bug."
    )
    text = " ".join(p.read_text(encoding="utf-8", errors="ignore") for p in vector)
    assert re.search(r"version|release|pin", text, re.I), (
        "REP: the vector and the clients that run it are reused together but "
        "released separately. No mechanism binds them."
    )


def test_falsify_c41_readme_first_sentence_is_true():
    """
    Probe P7 (Category H): does the repo scream what it does?

    Finding: README.md's first substantive sentence reads "Shared Appwrite client
    library for the VIEWS platform. Extracts the duplicated Appwrite storage,
    metadata, and caching logic ... into a single, independently versioned
    package." Present tense, and false -- the correction ("ships no code") is on
    line 5. tests/ holds falsification stubs and nothing else; there is no source
    directory. The repo screams "client library"; it is a document home.
    Severity: hard

    Expected: the opening sentence describes what the repo IS, before it
    describes what it may become.
    """
    lines = [line.strip() for line in (REPO / "README.md").read_text(encoding="utf-8").split("\n")]
    first_prose = next(line for line in lines if line and not line.startswith("#"))
    claims_to_be_a_library = re.search(r"^Shared Appwrite client library", first_prose)
    assert not claims_to_be_a_library, (
        "README's first sentence claims this repo IS a shared client library. "
        f"It ships no code. First sentence: {first_prose!r}"
    )


def test_falsify_c36_platform_reasons_in_the_stated_principles():
    """
    Probe P2 (Category H): does the platform's own governance use the principles
    the maintainer actually wants?

    Finding: across the entire þing-02 record, whole-word counts are SRP 0, OCP 0,
    LSP 0, ISP 0, REP 0, CCP 0, CRP 0, ADP 0, SDP 0, SAP 0. In prose: "reason to
    change" 0 files, "acyclic" 0, stable-dependency phrasing 0, file-layout/one-
    class 0. The decisions frequently COINCIDE with the principles (§5.8 is
    WET-before-DRY; refusing to depend on a parked repo is SDP; three thin clients
    is CRP) but were derived from precedent and from one repo's parked status --
    not from the principles. A decision that agrees with a principle by accident
    can drift from it just as accidentally.
    Severity: hard. This prediction was WRONG in the audit -- partial survival was
    predicted; it falsified outright.

    Expected: the admission test in §1 (or its record) asks which principle a rule
    serves, so agreement is derived rather than coincidental.
    """
    text = CONTRACT.read_text(encoding="utf-8")
    principled = re.search(
        r"\b(SRP|OCP|LSP|ISP|DIP|REP|CCP|CRP|ADP|SDP|SAP)\b|reason to change|"
        r"acyclic|depend.{0,20}stab",
        text,
    )
    assert principled, (
        "Neither PLATFORM-001 nor the admission test it cites reasons in the "
        "component/SOLID principles the platform is actually steered by. "
        "Adding 'which principle does this serve?' to the §1 test costs a sentence."
    )


def test_falsify_c35_clone_path_is_not_blocked_on_undated_work():
    """
    Probe P1 (Category D): can un-crafdapi be cut this week?

    Finding: orð_dómr §III(1) requires operator gate (a) -- classify the value in
    faoapi's history, rotate and scrub if live -- resolved before EITHER clone is
    cut; §III(7) requires F4(a) (views-faoapi#322) shipped first, because faoapi's
    own client carries a second C-231-class collapse at appwrite.py:1342-1352 that
    is dead by non-invocation rather than by a guard, and therefore ACTIVATES in
    any clone that adds a write route -- which views-productionapi is by
    definition. Neither has a date.
    Severity: hard (falsifies H2).

    NOT bureaucracy: both stop something genuinely bad being copied into two new
    repos. Cost is one ~30-minute console session plus a ~3-line fix.

    Expected: this test goes green when the operator record shows (a) closed and
    views-faoapi#322 merged. Until then the clones are correctly blocked.
    """
    record = WORKSPACE / "þingit" / "02_credential_identity_key_ownership" / "issues.gh"
    assert record.exists(), "þing-02 ledger missing; cannot check clone preconditions"
    ledger = record.read_text(encoding="utf-8")
    f4_open = re.search(r"\|\s*F4\s*\|.*\|\s*(created|proposed|in-progress|owed)\s*\|", ledger)
    assert not f4_open, (
        "views-faoapi#322 (F4 -- the second C-231, clone-activated) is not closed. "
        "orð_dómr §III(7) makes it a precondition of cutting EITHER clone: the defect "
        "is dead in faoapi by non-invocation, not by a guard, so it travels to any "
        "clone that adds a write route."
    )
