"""
Falsification test stubs for claim: "we have enough information to start setting
up this repo - orthogonal angle" (round 2: external reality & operational sufficiency)
Generated by /falsify audit on 2026-06-12

These tests are in TDD RED state -- they FAIL against the current repository.
Fix the documentation to make them pass, then re-run /falsify to verify.

Round 1 stubs live in test_falsification_enough_info_to_set_up_repo.py.
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
README = (REPO / "README.md").read_text(encoding="utf-8")


def test_falsify_r2_01_roadmap_consumed_source_repo_sdk_decision():
    """
    Probe 1 (Category A/B): Source-repo reality check.

    Finding: views-faoapi ratified ADR-019 (2026-05-29, three days BEFORE the
    roadmap was written) pinning `appwrite==19.2.0` exactly -- after discovering
    its declared pin (13.3.0) diverged from its runtime (19.2.0). ADR-019 also
    documents that SDK 19.2.0 deprecates `databases.list_documents()` (5 call
    sites in the code views-appwrite will extract into MetadataManager), with
    tripwire tests in test_sdk_compat.py. The roadmap's SDK Compatibility
    section frames the world as "SDK 13 vs 14+", proposes `appwrite>=5.0.0`,
    and mentions none of this.
    Severity: hard

    Expected: The roadmap acknowledges the source repo's ratified SDK state
    (19.2.0 pin, list_documents deprecation) in its SDK Compatibility section.
    """
    assert "19.2.0" in README or "list_documents" in README, (
        "README's SDK strategy ignores views-faoapi ADR-019 (appwrite==19.2.0 "
        "exact pin, 2026-05-29) and the list_documents deprecation affecting "
        "5 call sites slated for extraction into MetadataManager"
    )


def test_falsify_r2_02_facade_return_contracts_specified():
    """
    Probe 2 (Category D): Facade signature derivability.

    Finding: Of the six DatastoreManager methods (README:92-98), the return
    contracts of get_latest(), search(), and list_all() are specified nowhere
    (file ID? metadata dict? OperationResult.data shape?). The Phase-2 wrapper
    example (README:365-366) names its method get_latest_file_id but returns
    get_latest()'s output unmodified, deepening the ambiguity. download() is
    dual-mode (bytes vs save_path) with the data key "file_bytes" mentioned
    once in passing (README:257); upload()'s .data payload is unspecified.
    Severity: soft

    Expected: A DatastoreManager intent contract (docs/CICs/DatastoreManager.md
    per ADR-006) or equivalent specifies each method's parameters, return
    shape, and error behavior.
    """
    cic = REPO / "docs" / "CICs" / "DatastoreManager.md"
    assert cic.exists(), (
        "No DatastoreManager contract exists; 3+ of 6 facade method return "
        "contracts cannot be written from the docs without guessing"
    )


def test_falsify_r2_03_integration_test_isolation_specified():
    """
    Probe 3 (Category F/H): Test-vs-production isolation.

    Finding: The live integration lifecycle creates and deletes buckets
    (README:512-525) gated only on APPWRITE_TEST_ENDPOINT being set -- and no
    document states that this endpoint must target an isolated test project.
    The only concrete endpoint+project_id anywhere in the corpus is the
    production-looking pair (README:269-270). The documented default path for
    "run integration tests" therefore points destructive operations at the
    production Appwrite project.
    Severity: hard

    Expected: The testing strategy states that APPWRITE_TEST_ENDPOINT must
    reference a dedicated test project/instance, never the production project.
    """
    corpus = README + "".join(
        p.read_text(encoding="utf-8") for p in (REPO / "docs").rglob("*.md")
    )
    isolation = re.search(
        r"APPWRITE_TEST_ENDPOINT[^.]*?(test (project|instance)|never[^.]*production|not[^.]*production)",
        corpus,
        re.I | re.S,
    )
    assert isolation, (
        "No document specifies that integration tests must run against an "
        "isolated test project; the only documented endpoint is production"
    )


def test_falsify_r2_04_first_commit_gate_sequencing_documented():
    """
    Probe 5 (Category H): First-commit gate sequencing.

    Finding: No document defines the order of operations for the first code
    commit under the interlocking gates: ADR-005 (no merge without tests),
    the ship-it pytest gate (intentionally RED from round-1 falsification
    stubs), ADR-006 (CIC timing), C-02's scaffold-time CI trigger. As of this
    audit the deadlock is live: ship-it cannot pass while the TDD-red stubs
    exist, and no document says whether to waive, sequence, or burn down.
    Severity: soft

    Expected: A contribution document (e.g. contributor protocol section or
    CONTRIBUTING.md) defines the first-commit definition-of-done and how
    falsification-stub RED states interact with the ship-it/test gates.

    RESOLVED 2026-06-12: "Gate Sequencing for Pre-Code Commits" added to
    docs/contributor_protocols/carbon_based_agents.md. This test now verifies
    the section exists.
    """
    protocol = (
        REPO / "docs" / "contributor_protocols" / "carbon_based_agents.md"
    ).read_text(encoding="utf-8")
    assert "Gate Sequencing" in protocol and "falsification" in protocol.lower(), (
        "The gate-sequencing section is missing from the carbon protocol; "
        "no documented sequence lets commits land alongside TDD-red stubs"
    )
