"""
Falsification test stubs for claim: "we have enough information to start setting up this repo"
Generated by /falsify audit on 2026-06-12

These tests are in TDD RED state -- they FAIL against the current repository.
Fix the documentation/scaffold to make them pass, then re-run /falsify to verify
and check for regressions.

NOTE: This file makes the `ship-it` pytest gate red on purpose. That is the
TDD-red contract of the falsification audit, not an accident.
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
README = (REPO / "README.md").read_text(encoding="utf-8")


def test_falsify_01_scaffold_buildable_without_invented_values():
    """
    Probe 1 (Category D): Dry-run scaffold from documented values only.

    Finding: The build succeeds but four decisions are nowhere documented
    (requires-python, license, description, authors). The resulting wheel is
    tagged `py2.py3-none-any` -- the artifact silently claims Python 2 support
    because no Python floor is specifiable from the docs.
    Severity: soft

    Expected: A committed pyproject.toml exists declaring requires-python,
    so the built artifact carries a correct python tag.
    """
    pyproject = REPO / "pyproject.toml"
    assert pyproject.exists(), "No pyproject.toml exists; scaffold decisions remain undocumented"
    assert "requires-python" in pyproject.read_text(encoding="utf-8"), (
        "pyproject.toml must declare requires-python; without it the wheel "
        "silently claims py2.py3 universal compatibility"
    )


def test_falsify_02_sdk_pin_consistent_with_compat_narrative():
    """
    Probe 2 (Category E): SDK pin vs SDK-13/14 compat narrative vs PyPI reality.

    Finding: README pins `appwrite>=5.0.0` while the compat design discusses
    only SDK 13 and 14+. PyPI's actual latest major is 20 (20.1.0). The pin
    admits majors 5-12 (predating the narrative) and resolves today to major
    20 (six majors past the narrative's frontier, never examined). The single
    runtime dependency line cannot be copied verbatim as the docs intend.
    Severity: hard

    Expected: The documented pin's floor is at least the lowest SDK major the
    compat layer claims to handle (13), and the docs acknowledge the actual
    current major.
    """
    m = re.search(r'"appwrite>=(\d+)\.', README)
    assert m, "README no longer documents an appwrite pin -- update this test"
    floor = int(m.group(1))
    assert floor >= 13, (
        f"README pins appwrite>={floor}.0.0 but the compat narrative "
        f"(README SDK Compatibility section) only covers SDK 13/14+; "
        f"majors {floor}-12 are admitted but never designed for, and PyPI "
        f"is at major 20"
    )


def test_falsify_03_ci_gate_is_specified():
    """
    Probe 3 (Category B): CI/lint gate specifiability at scaffold time.

    Finding: CI is presupposed five times (README:236,491,525; ADR-005:93-94)
    but no document specifies a CI system, workflow, lint config, or Python
    matrix. Risk register C-02's trigger fires at the scaffold commit and
    cannot be satisfied from the docs.
    Severity: hard

    Expected: A CI workflow exists (or a committed CI specification document)
    implementing the ruff + pytest + boundary-enforcement gates that ADR-005
    and C-02 demand.
    """
    workflows = list((REPO / ".github" / "workflows").glob("*.yml")) + list(
        (REPO / ".github" / "workflows").glob("*.yaml")
    )
    assert workflows, (
        "No CI workflow exists; ADR-005 enforcement and C-02's scaffold-time "
        "trigger presuppose CI that no document specifies"
    )


def test_falsify_04_public_surface_internally_consistent():
    """
    Probe 4 (Category E): Public API surface consistency.

    Finding: README:261 declares a 3-name public API ("Everything else is
    internal") while README:382 instructs consumers to import the
    underscore-private `_as_dict`/`_get` from `views_appwrite.compat`.
    The scaffolder cannot write `__init__.py` or choose compat function
    naming without resolving this contradiction.
    Severity: soft

    Expected: One coherent specification -- either compat helpers are public
    (no underscore prefix, exported) or consumers are given a public wrapper.
    """
    # TODO: Replace with a check of the actual __init__.py exports once code exists.
    assert False, (
        "README:261-265 (3 exports, 'everything else is internal') contradicts "
        "README:382 (consumers must import _as_dict/_get from views_appwrite.compat)"
    )


def test_falsify_05_license_and_python_floor_decided():
    """
    Probe 5 (Category H): Scaffold adequacy vs standard Python library setup.

    Finding: Zero mentions of a license, requires-python, or .gitignore in
    the entire corpus. An org-distributed pip-installable package without a
    license decision would be blocked by any competent reviewer; the missing
    Python floor produced the py2.py3 wheel tag in Probe 1.
    Severity: hard (license, python floor) / soft (.gitignore)

    Expected: LICENSE file (or pyproject license field) and requires-python
    exist; .gitignore covers Python build/test artifacts.
    """
    has_license = (REPO / "LICENSE").exists() or (REPO / "LICENSE.md").exists()
    pyproject = REPO / "pyproject.toml"
    has_license = has_license or (
        pyproject.exists() and "license" in pyproject.read_text(encoding="utf-8")
    )
    assert has_license, "No license decision exists anywhere in the repository"
    assert (REPO / ".gitignore").exists(), "No .gitignore; first pytest run pollutes the tree"


def test_falsify_06_appwriteconfig_has_single_authoritative_field_list():
    """
    Probe 6 (Category E): AppwriteConfig field-list authority.

    Finding: Four partial, disagreeing enumerations: README:57 (includes
    auth_method, cache TTL, timeout; omits cache_dir), README:268-276 example
    (7 fields; omits auth_method, TTL, timeouts), ADR-009:41 (adds cache_dir,
    plural timeouts), README:501 (derived bucket_name/database_name in no
    list). No single authoritative enumeration exists to write even a stub.
    Severity: soft (cross-ref register C-04)

    Expected: One authoritative field list (candidate ADR-012 or a CIC)
    from which the dataclass can be written.
    """
    # TODO: Replace with a check against the ratified field-list artifact
    # (ADR-012 or CIC) once it exists.
    assert False, (
        "Four partial AppwriteConfig field enumerations disagree "
        "(README:57 vs :268-276 vs :501 vs ADR-009:41); no authoritative list"
    )
